name: Build Geode Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Geode CLI
        run: npm i -g @geode-sdk/cli

      - name: Build Mod
        run: geode build --config release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-mod
          path: build/*.geode